Feature/social login
team-between-leaf/team-leaf-backend pull request #28
Opened 2024-03-06 10:55 UTC by hershyYJ

## ✔ 지라 이슈 번호

## 📒 작업 내용

- 소셜 로그인 api 추가 (회원가입, 로그인, 로그아웃, 중복 회원 조회)

- 중복 회원 조회 : 자체 로그인으로 가입된 유저면 "일반 로그인으로 가입된 계정이 존재합니다.", 소셜 로그인으로 가입된 유저면 socialType + "로그인으로 가입된 계정이 존재합니다." 출력

- 비밀번호 검증 (AccountService) : 최소 9, 최대 21자리에서 최대 22자리로 검증식 수정

- role (AccountRole) : 기존 user, guest, admin에서 user, seller, admin으로 권한 수정

## 📢 리뷰어에게 하고 싶은 말
ex) 어디어디를 중점적으로 봐주세요 ...

## 📌 PR 전 체크 사항

2024-03-06 12:38 UTC, 5tr1ker requested changes

2024-03-06 12:38 UTC, 5tr1ker commented on src/main/java/com/team/leaf/user/account/service/AccountService.java
> +        String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{9,22}$";
최소 6자부터 가능한걸로 알고있는데 9자부터 비밀번호를 입력받게 수정된거야?

2024-03-07 12:00 UTC, hershyYJ commented on src/main/java/com/team/leaf/user/account/service/AccountService.java
> +        String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{9,22}$";
엉 저번에 수정하기로 하고 다음 날인가? 정원 개발자랑 이야기 해봤는데 최소 글자는 9자로 받는 걸로 수정하고, 최대만 21자에서 22자로 늘려달라는 요청을 받아서 그렇게만 수정했어!

2024-03-08 09:44 UTC, 5tr1ker approved these changes

2024-03-08 09:45 UTC, merged