[feat] jwt 회원 가입, 로그인, 로그아웃 기능 추가
team-between-leaf/team-leaf-backend pull request #8
Opened 2024-02-02 11:57 UTC by hershyYJ

## 📒 작업 내용
- jwt 회원 가입, 로그인, 로그아웃 기능 추가
- 회원 가입 시, 성공 여부 리턴 및 account_detail 테이블에 유저 정보 저장
- 로그인 시, 성공 여부, access token, refresh token 리턴 및 refresh_token 테이블에 refresh token 저
- 로그아웃 시, 성공 여부 리턴
- dto를 request, response 패키지로 분류

## 📢 리뷰어에게 하고 싶은 말
- refresh 토큰을 헤더에 넣어 access token을 갱신하도록 issuedToken 메서드를 작성했는데 userDetails가 null로 반환되는 문제를 확인하여 추후 개선 예정입니다. 혹시 오류 원인을 파악하신 분이 계시다면 연락 주시면 감사하겠습니다.....

- yaml 파일에 jwt.secret 값은 보안상 우선 추가해 놓지 않았습니다. 관련 값은 노션에 작성해 놓거나 필요하실 때 연락 주시면 보내드리도록 하겠습니다.

2024-02-02 17:18 UTC, 5tr1ker requested changes

2024-02-02 17:18 UTC, 5tr1ker commented on build.gradle
> +	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
jjwt 관련 라이브러리가 3개로 나뉘어져 있어 보이는데, 
implementation 'io.jsonwebtoken:jjwt:0.11.5
를 추가하여 api 와 impl , jackson 을 모두 포함하는 라이브러리를 사용하시는 건 어떠신가요?

여러 모듈을 각각 가져오는 것은 각 모듈의 버전을 일치시키기 어렵고, 유지보수가 번거로울 수 있습니다. 하나의 종속성으로 전체 라이브러리를 가져오면 해당 라이브러리의 버전을 통일하고, 관련 모듈들이 함께 업데이트되므로 일관성을 유지하는 데 도움이 될 거 같아 의견을 내봅니다.

2024-02-02 17:18 UTC, 5tr1ker commented on src/main/java/com/team/leaf/user/account/config/BCryptConfig.java
> +}
해당 BCrypeConfig 파일은 JwtSecurityConfig ( Security Config ) 파일과 통합할 수 있는데, 보안 관련 로직은 Security Config에 통합하는 건 어떠신가요?

2024-02-02 17:18 UTC, 5tr1ker commented on src/main/java/com/team/leaf/user/account/controller/AccountController.java
>  }
혹시 ResponseEntity 클래스를 뺀 이유가 있을까용? ApiResponse 클래스로 응답 코드를 직접 설정했다면 큰 문제가 없을 거 같지만 궁금해서 남겨봅니다..!

2024-02-02 17:18 UTC, 5tr1ker commented on src/main/java/com/team/leaf/user/account/jwt/PrincipalDetailsService.java
> +    }
print 문은 로그를 위해 일부로 남겨 놓으신건가요?

로그라면 Slf4j 를 활용하는 건 어떠신가요

2024-02-03 05:44 UTC, hershyYJ commented on build.gradle
> +	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
해당 부분 및 securityconfig 관련 통합 부분 참고해서 수정해 pr 올리도록 하겠습니다. 좋은 의견 감사합니다.

2024-02-03 05:46 UTC, hershyYJ commented on src/main/java/com/team/leaf/user/account/controller/AccountController.java
>  }
이전에 프로젝트 진행하면서 웹 프론트 분께서 본인이 프로젝트 진행할 때 백엔드에서 ApiResponse를 활용해서 응답을 주신 적이 있는데 반환 형식이 일치하다보니 더 가독성이 좋았던 것 같다는 의견을 주셨던 게 생각이 나서 ApiResponse를 사용해 보았습니다. 사실 어떻게 작성하든 기능은 큰 차이가 없다보니 ResponseEntity 형식으로 수정해도 상관은 없습니다. 관련하여 추가 의견 주시면 좋을 것 같습니다.

2024-02-03 05:46 UTC, hershyYJ commented on src/main/java/com/team/leaf/user/account/jwt/PrincipalDetailsService.java
> +    }
해당 부분 같은 경우는 주석 처리해 놓은 코드가 기존 코드이고 아래 코드는 로그 확인을 위한 코드가 맞습니다. 제가 access token 재발급 관련 코드에 문제가 있다고 pr 올릴 때 작성해 놓았는데, PrincipalDetailsService 클래스에 문제가 있지 않을까 생각 되어 Slf4j, Logger를 사용해 보았음에도 아무 로그가 나오지 않았고 혹시 몰라 print문을 추가로 작성해 보았습니다. 그리고 print문도 출력되지 않는 것을 보고 호출이 제대로 이뤄지지 않고 있음을 파악했고, 관련하여 코드 수정을 진행할 예정입니다. 이때문에 print문이 현재 남아 있는 상태인 것이고 해당 부분 관련해서는 추후 다시 pr 올릴 때는 삭제될 것 같습니다.

2024-02-03 12:34 UTC, bbungjin approved these changes

2024-02-03 12:59 UTC, 5tr1ker approved these changes

2024-02-08 05:39 UTC, merged